---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---


<!--Include academic icons or buttons-->
{{< include /files/includes/_academic.qmd >}}

Notes: ^\*^ corresponding author; ^†^ equal contribution.

## Journal Papers

Smer-Barreto, V.^\*^, Quintanilla, A., Elliott, R. J. R., Dawson, J. C., **Sun, J.**, Campa, V. M., Lorente-Macias, A., Unciti-Broceta, A., Carragher, N. O., Acosta, J. C., & Oyarzún, D. A. (2023). [Discovery of senolytics using machine learning](posts/paper-title/senolytics.qmd). *Nature Communications*, 14, 3445. \[[pdf](https://www.nature.com/articles/s41467-023-39120-1.pdf)\] <span class="__dimensions_badge_embed__" data-doi="10.1038/s41467-023-39120-1" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.1038/s41467-023-39120-1" data-hide-no-mentions="true" class="altmetric-embed"></div>

**Key Words**: Applied Machine Learning; Drug Discovery

## Conference Proceedings

**Sun, J.**^\*^, Sevastjanova, R.^†^, Ahmadi, S.^†^, Sennrich, R., & El-Assady, M. (2025). [Dia-Lingle: A Gamified Interface for Dialectal Data Collection](posts/paper-title/dialingle.qmd). *Proceedings of the 63rd Annual Meeting of the Association for Computational Linguistics (Volume 3: System Demonstrations)*, 148-158. \[[pdf](https://aclanthology.org/2025.acl-demo.15.pdf)\] <span class="__dimensions_badge_embed__" data-doi="10.18653/v1/2025.acl-demo.15" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.18653/v1/2025.acl-demo.15" data-hide-no-mentions="true" class="altmetric-embed"></div>     

**Key Words**: Low-resouerced NLP; Gamification; Visualisation

## Conference Workshops & Findings

Ni, W., **Sun, J.**, Liu, Y., & El-Assady, M. (2026). [Cross-Cultural Simulation of Citizen Emotional Responses to Bureaucratic Red Tape Using LLM Agents](https://chi2026.acm.org/workshops/accepted/#w45-polisimchi-2026-llm-agent-simulation-for-policy). 
*PoliSim@CHI 2026: LLM Agent Simulation for Policy*. DOI coming soon.
<div></div>
**Key Words**: LLMs, Agent-Simulation, Public Administration

<hr style="width:85%">

Laguna, S.^†^, Heidenreich, J.^†^, **Sun, J.**^†^, Cetin, N.^†^, Al-Hazwani, I., Schlegel, U., Cheng, F., & El-Assady, M. (2023). 
[ExpLIMEable: A Visual Analytics Approach for Exploring LIME](posts/paper-title/lime.qmd). *IEEE VIS 2023 Workshop on Visualisation for AI Explainability in Healthcare (VAHC)*. \[[pdf](https://el-assady.com/publication/2023lagunaexplimeable/2023lagunaexplimeable.pdf)\] \[[doi](https://doi.org/10.1109/VAHC60858.2023.00011)\] <span class="__dimensions_badge_embed__" data-doi="10.1109/VAHC60858.2023.00011" data-style="large_rectangle"></span> <div data-badge-popover="right" data-badge-type="1" data-doi="10.1109/VAHC60858.2023.00011" data-hide-no-mentions="true" class="altmetric-embed"></div>

**Key Words**: Explainable AI; Visualisation; LIME; Healthcare

<hr style="width:85%">

Laguna, S.^†^, Heidenreich, J.^†^, **Sun, J.**^†^, Cetin, N.^†^, Al-Hazwani, I., Schlegel, U., Cheng, F., & El-Assady, M. (2023). 
[ExpLIMEable: A Visual Analytics Approach for Exploring LIME](https://openreview.net/forum?id=81FSrQxgEv). *XAI in Action: Past, Present, and Future Applications (NeurIPS XAIA 2023)*. \[[pdf](https://openreview.net/pdf?id=81FSrQxgEv)\] \[[OpenReview](https://openreview.net/forum?id=81FSrQxgEv)\] 

## Preprints

Daniels, S.^†^, **Sun, J.**^†^, Xie, J. (2023). 
[CADA-GAN: Context-Aware GAN with Data Augmentation](https://arxiv.org/abs/2301.08849). *Arxiv*. \[[pdf](https://arxiv.org/pdf/2301.08849)\]
<span class="__dimensions_badge_embed__" data-doi="10.48550/arXiv.2301.08849" data-style="large_rectangle"></span>
<div data-badge-popover="right" data-badge-type="1" data-doi="10.48550/arXiv.2301.08849" data-hide-no-mentions="true" class="altmetric-embed"></div>

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}